"""Turning one learner's signals into four sentences a parent can use.

Every sentence here is written in advance and chosen by evidence. Nothing is
generated by a model and nothing is interpolated from a number, because the
screen this feeds is defined by what it must not say: no scores, no
percentages, no labels, no clinical terms. A template that cannot hold a
number cannot leak one.

The comparison is against the previous window of the same length, so
"more than before" always means the same thing.
"""
from nevo.domain.parents.vocabulary import GrowthDimension, GrowthTrend
from nevo.parents.entities import GrowthSignals, GrowthStatement

MINIMUM_SESSIONS = 5
"""Below this there is no term to describe, only a handful of lessons."""

RELATIVE_CHANGE = 0.15
"""How far a measure has to move before it is a change and not noise."""

_STATEMENTS: dict[tuple[GrowthDimension, GrowthTrend], str] = {
    (GrowthDimension.STAYING_WITH_HARD_PROBLEMS, GrowthTrend.GROWING): (
        "{name} is working through tricky questions alone for longer before "
        "asking for help."
    ),
    (GrowthDimension.STAYING_WITH_HARD_PROBLEMS, GrowthTrend.STEADY): (
        "{name} keeps going when a question gets harder, much as before."
    ),
    (GrowthDimension.STAYING_WITH_HARD_PROBLEMS, GrowthTrend.EMERGING): (
        "{name} is starting to stay with harder questions, though it is early "
        "to call it a habit."
    ),
    (GrowthDimension.KNOWING_WHAT_SHE_KNOWS, GrowthTrend.GROWING): (
        "{name} has a clearer sense of what has been understood, and asks for "
        "things to be explained differently at the right moments."
    ),
    (GrowthDimension.KNOWING_WHAT_SHE_KNOWS, GrowthTrend.STEADY): (
        "{name} is generally aware of what has been understood and what still "
        "needs another look."
    ),
    (GrowthDimension.KNOWING_WHAT_SHE_KNOWS, GrowthTrend.EMERGING): (
        "{name} is beginning to notice when something has not quite landed."
    ),
    (GrowthDimension.CONNECTING_IDEAS, GrowthTrend.GROWING): (
        "{name} is carrying what is learnt in one subject into another."
    ),
    (GrowthDimension.CONNECTING_IDEAS, GrowthTrend.STEADY): (
        "{name} works steadily across more than one subject."
    ),
    (GrowthDimension.CONNECTING_IDEAS, GrowthTrend.EMERGING): (
        "{name} has started working across more than one subject."
    ),
    (GrowthDimension.LEARNING_NEW_THINGS_FASTER, GrowthTrend.GROWING): (
        "New ideas are landing more quickly for {name} than they were before."
    ),
    (GrowthDimension.LEARNING_NEW_THINGS_FASTER, GrowthTrend.STEADY): (
        "{name} is picking up new ideas at a steady pace."
    ),
    (GrowthDimension.LEARNING_NEW_THINGS_FASTER, GrowthTrend.EMERGING): (
        "{name} is beginning to build up ideas that will hold."
    ),
}

_NOT_ENOUGH: dict[GrowthDimension, str] = {
    GrowthDimension.STAYING_WITH_HARD_PROBLEMS: (
        "There have not been enough lessons yet to say how {name} handles "
        "harder questions."
    ),
    GrowthDimension.KNOWING_WHAT_SHE_KNOWS: (
        "There have not been enough lessons yet to say how well {name} can "
        "tell what has been understood."
    ),
    GrowthDimension.CONNECTING_IDEAS: (
        "{name} has not worked across enough subjects yet for us to say."
    ),
    GrowthDimension.LEARNING_NEW_THINGS_FASTER: (
        "There have not been enough lessons yet to say how quickly new ideas "
        "are landing for {name}."
    ),
}


def compose(
    *,
    name: str,
    current: GrowthSignals,
    previous: GrowthSignals,
) -> tuple[GrowthStatement, ...]:
    return tuple(
        _statement(dimension, name, _trend(dimension, current, previous))
        for dimension in GrowthDimension
    )


def headline_and_summary(
    *,
    name: str,
    statements: tuple[GrowthStatement, ...],
) -> tuple[str, str]:
    described = [
        item for item in statements if item.trend is not GrowthTrend.NOT_ENOUGH_YET
    ]
    if not described:
        return (
            f"How {name} is getting on",
            _sentence(
                f"{name} has not had enough lessons on Nevo yet for us to describe "
                "how the term is going. This page will fill in as that changes."
            ),
        )
    growing = [item for item in described if item.trend is GrowthTrend.GROWING]
    if growing:
        return (
            f"How {name} is growing",
            _sentence(
                f"Here is what we have noticed about the way {name} is learning "
                "this term. None of it is a score, and none of it is a comparison "
                "with anyone else."
            ),
        )
    return (
        f"How {name} is getting on",
        _sentence(
            f"{name} is holding steady this term. Here is what we have noticed "
            "about how the learning is going."
        ),
    )


def _statement(
    dimension: GrowthDimension,
    name: str,
    trend: GrowthTrend,
) -> GrowthStatement:
    template = (
        _NOT_ENOUGH[dimension]
        if trend is GrowthTrend.NOT_ENOUGH_YET
        else _STATEMENTS[(dimension, trend)]
    )
    # No pronouns at all. The roster holds none for a learner, guessing one
    # from a name misgenders a real child, and "they" forces verb agreement
    # into every template for no gain.
    return GrowthStatement(
        dimension=dimension,
        trend=trend,
        statement=_sentence(template.format(name=name)),
    )


def _sentence(text: str) -> str:
    """Capitalise the opening letter only.

    The name is lower case when we do not have one ("your child"), so it must
    read correctly mid-sentence and be lifted at the start rather than title
    cased everywhere.
    """
    return text[:1].upper() + text[1:] if text else text


def _trend(
    dimension: GrowthDimension,
    current: GrowthSignals,
    previous: GrowthSignals,
) -> GrowthTrend:
    if current.sessions < MINIMUM_SESSIONS:
        return GrowthTrend.NOT_ENOUGH_YET
    if dimension is GrowthDimension.STAYING_WITH_HARD_PROBLEMS:
        return _direction(
            _ratio(current.completed_sessions, current.sessions),
            _ratio(previous.completed_sessions, previous.sessions),
            has_baseline=previous.sessions >= MINIMUM_SESSIONS,
        )
    if dimension is GrowthDimension.KNOWING_WHAT_SHE_KNOWS:
        return _direction(
            _ratio(current.self_adjustments + current.comprehension_responses, current.sessions),
            _ratio(
                previous.self_adjustments + previous.comprehension_responses,
                previous.sessions,
            ),
            has_baseline=previous.sessions >= MINIMUM_SESSIONS,
        )
    if dimension is GrowthDimension.CONNECTING_IDEAS:
        if current.subjects_touched < 2:
            return GrowthTrend.NOT_ENOUGH_YET
        return _direction(
            float(current.subjects_touched),
            float(previous.subjects_touched),
            has_baseline=previous.sessions >= MINIMUM_SESSIONS,
        )
    if current.concepts_confident == 0:
        return GrowthTrend.NOT_ENOUGH_YET
    if current.practice_per_confident_concept is None:
        return GrowthTrend.EMERGING
    if previous.practice_per_confident_concept is None:
        return GrowthTrend.EMERGING
    # Fewer attempts per idea understood is faster, so the comparison inverts.
    return _direction(
        previous.practice_per_confident_concept,
        current.practice_per_confident_concept,
        has_baseline=previous.concepts_confident > 0,
    )


def _ratio(part: int, whole: int) -> float:
    return part / whole if whole else 0.0


def _direction(current: float, previous: float, *, has_baseline: bool) -> GrowthTrend:
    if not has_baseline:
        # A first term has nothing to be growing against.
        return GrowthTrend.EMERGING
    if previous <= 0:
        return GrowthTrend.EMERGING if current > 0 else GrowthTrend.NOT_ENOUGH_YET
    change = (current - previous) / previous
    if change >= RELATIVE_CHANGE:
        return GrowthTrend.GROWING
    return GrowthTrend.STEADY
